package main.java.com.hotel.model;
// Generated 19 avr. 2017 12:27:09 by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "hotel")
public class Categorie implements java.io.Serializable {

	private Integer idCategorie;
	private String nom;
	private String description;
	private Double prix;
	private Set<Chambre> chambres = new HashSet(0);

	public Categorie() {
	}

	public Categorie(String nom, String description, Double prix, Set chambres) {
		this.nom = nom;
		this.description = description;
		this.prix = prix;
		this.chambres = chambres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategorie", unique = true, nullable = false)
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "nom", length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "prix", precision = 22, scale = 0)
	public Double getPrix() {
		return this.prix;
	}

	public void setPrix(Double prix) {
		this.prix = prix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Chambre> getChambres() {
		return this.chambres;
	}

	public void setChambres(Set<Chambre> chambres) {
		this.chambres = chambres;
	}

}
