package main.java.com.hotel.model;
// Generated 30 avr. 2017 02:56:43 by Hibernate Tools 5.2.0.CR1

import javafx.beans.property.*;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "hotel")
public class Categorie implements java.io.Serializable {

    private IntegerProperty idCategorie;
    private StringProperty nom;
    private DoubleProperty prix;

    public Categorie() {
        idCategorie = new SimpleIntegerProperty();
        this.nom = new SimpleStringProperty();
        this.prix = new SimpleDoubleProperty();
    }

    public Categorie(String nom, Double prix) {
        idCategorie = new SimpleIntegerProperty();
        this.nom = new SimpleStringProperty(nom);
        this.prix = new SimpleDoubleProperty(prix);

    }

    public IntegerProperty idCategorieProperty() {
        return idCategorie;
    }


    public StringProperty nomProperty() {
        return nom;
    }


    public DoubleProperty prixProperty() {
        return prix;
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idCategorie", unique = true, nullable = false)
    public Integer getIdCategorie() {
        return this.idCategorie.get();
    }

    public void setIdCategorie(Integer idCategorie) {
        this.idCategorie.set(idCategorie);
    }

    @Column(name = "nom", length = 20)
    public String getNom() {
        return this.nom.get();
    }

    public void setNom(String nom) {
        this.nom.set(nom);
    }

<<<<<<< HEAD
    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description.get();
    }

    public void setDescription(String description) {
        this.description.set(description);
    }
=======
>>>>>>> origin/master

    @Column(name = "prix", precision = 22, scale = 0)
    public Double getPrix() {
        return this.prix.get();
    }

    public void setPrix(Double prix) {
        this.prix.set(prix);
    }

    @Override
    public String toString() {
        return getNom();
    }


}
