package main.java.com.hotel.model;
// Generated 30 avr. 2017 02:56:43 by Hibernate Tools 5.2.0.CR1

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.property.SimpleIntegerProperty;
import org.hibernate.annotations.Cascade;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Chambre generated by hbm2java
 */
@Entity
@Table(name = "chambre", catalog = "hotel")
public class Chambre implements java.io.Serializable {

    private IntegerProperty idChambre;
    private Categorie categorie;
    private IntegerProperty numeroChambre;
    private IntegerProperty etage;
    private BooleanProperty check;

    public Chambre() {
        this.idChambre = new SimpleIntegerProperty();

        this.numeroChambre = new SimpleIntegerProperty();
        this.etage = new SimpleIntegerProperty();
        this.check = new SimpleBooleanProperty();
    }

    public Chambre(int idChambre) {
        this.idChambre = new SimpleIntegerProperty(idChambre);
        this.numeroChambre = new SimpleIntegerProperty();
        this.etage = new SimpleIntegerProperty();
        this.check = new SimpleBooleanProperty();
    }

    public Chambre(int idChambre, Categorie categorie, Integer numeroChambre, Integer etage, Boolean check) {
        this.idChambre = new SimpleIntegerProperty(idChambre);
        this.categorie = categorie;
        this.numeroChambre = new SimpleIntegerProperty(numeroChambre);
        this.etage = new SimpleIntegerProperty(etage);
        this.check = new SimpleBooleanProperty(check);
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idChambre", unique = true, nullable = false)
    public int getIdChambre() {
        return this.idChambre.get();
    }

    public void setIdChambre(int idChambre) {
        this.idChambre.set(idChambre);
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @Cascade(org.hibernate.annotations.CascadeType.ALL)
    @JoinColumn(name = "id_categorie")
    public Categorie getCategorie() {
        return this.categorie;
    }

    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }

    @Column(name = "numeroChambre")
    public Integer getNumeroChambre() {
        return this.numeroChambre.get();
    }

    public void setNumeroChambre(Integer numeroChambre) {
        this.numeroChambre.set(numeroChambre);
    }

    @Column(name = "etage")
    public Integer getEtage() {
        return this.etage.get();
    }

    public void setEtage(Integer etage) {
        this.etage.set(etage);
    }

    @Column(name = "check")
    public Boolean getCheck() {
        return this.check.get();
    }

    public void setCheck(Boolean check) {
        this.check.set(check);

    }

    public IntegerProperty idChambreProperty() {
        return idChambre;
    }

    public IntegerProperty numeroChambreProperty() {
        return numeroChambre;
    }

    public IntegerProperty etageProperty() {
        return etage;
    }


    public BooleanProperty checkProperty() {
        return check;
    }
}
