package main.java.com.hotel.model;
// Generated 19 avr. 2017 12:27:09 by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;

/**
 * Chambre generated by hbm2java
 */
@Entity
@Table(name = "chambre", catalog = "hotel")
public class Chambre implements java.io.Serializable {

	private int idC;
	private Categorie categorie;
	private Integer numr;
	private Integer etage;
	private Boolean chack;

	public Chambre() {
	}

	public Chambre(int idC) {
		this.idC = idC;
	}

	public Chambre(int idC, Categorie categorie, Integer numr, Integer etage, Boolean chack) {
		this.idC = idC;
		this.categorie = categorie;
		this.numr = numr;
		this.etage = etage;
		this.chack = chack;

	}

	@Id

	@Column(name = "idC", unique = true, nullable = false)
	public int getIdC() {
		return this.idC;
	}

	public void setIdC(int idC) {
		this.idC = idC;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_categorie")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "numr")
	public Integer getNumr() {
		return this.numr;
	}

	public void setNumr(Integer numr) {
		this.numr = numr;
	}

	@Column(name = "etage")
	public Integer getEtage() {
		return this.etage;
	}

	public void setEtage(Integer etage) {
		this.etage = etage;
	}

	@Column(name = "chack")
	public Boolean getChack() {
		return this.chack;
	}

	public void setChack(Boolean chack) {
		this.chack = chack;
	}

}
