package main.java.com.hotel.model;
// Generated 19 avr. 2017 12:27:09 by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "hotel")
public class Client implements java.io.Serializable {

	private int idCl;
	private String nom;
	private String prenom;
	private Date dateNaiss;
	private String numTel;
	private Set<Reservation> reservations = new HashSet(0);

	public Client() {
	}

	public Client(int idCl) {
		this.idCl = idCl;
	}

	public Client(int idCl, String nom, String prenom, Date dateNaiss, String numTel, Set reservations) {
		this.idCl = idCl;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaiss = dateNaiss;
		this.numTel = numTel;
		this.reservations = reservations;
	}

	@Id

	@Column(name = "idCl", unique = true, nullable = false)
	public int getIdCl() {
		return this.idCl;
	}

	public void setIdCl(int idCl) {
		this.idCl = idCl;
	}

	@Column(name = "nom", length = 50)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateNaiss", length = 10)
	public Date getDateNaiss() {
		return this.dateNaiss;
	}

	public void setDateNaiss(Date dateNaiss) {
		this.dateNaiss = dateNaiss;
	}

	@Column(name = "numTel", length = 50)
	public String getNumTel() {
		return this.numTel;
	}

	public void setNumTel(String numTel) {
		this.numTel = numTel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

}
