package main.java.com.hotel.model;
// Generated 19 avr. 2017 12:27:09 by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.Date;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "hotel")
public class Facture implements java.io.Serializable {

	private int idP;
	private Reservation reservation;
	private Date datePaiement;
	private Double somme;

	public Facture() {
	}

	public Facture(int idP, Reservation reservation) {
		this.idP = idP;
		this.reservation = reservation;
	}

	public Facture(int idP, Reservation reservation, Date datePaiement, Double somme) {
		this.idP = idP;
		this.reservation = reservation;
		this.datePaiement = datePaiement;
		this.somme = somme;
	}

	@Id

	@Column(name = "idP", unique = true, nullable = false)
	public int getIdP() {
		return this.idP;
	}

	public void setIdP(int idP) {
		this.idP = idP;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idR", nullable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datePaiement", length = 10)
	public Date getDatePaiement() {
		return this.datePaiement;
	}

	public void setDatePaiement(Date datePaiement) {
		this.datePaiement = datePaiement;
	}

	@Column(name = "somme", precision = 22, scale = 0)
	public Double getSomme() {
		return this.somme;
	}

	public void setSomme(Double somme) {
		this.somme = somme;
	}

}
