package main.java.com.hotel.model;
// Generated 30 avr. 2017 02:56:43 by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.Date;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "hotel")
public class Facture implements java.io.Serializable {

	private int idFacture;
	private Date datePaiement;
	private Double somme;

	public Facture() {
	}

	public Facture(int idFacture) {
		this.idFacture = idFacture;
	}

	public Facture(int idFacture, Date datePaiement, Double somme) {
		this.idFacture = idFacture;
		this.datePaiement = datePaiement;
		this.somme = somme;

	}

	@Id

	@Column(name = "idFacture", unique = true, nullable = false)
	public int getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(int idFacture) {
		this.idFacture = idFacture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datePaiement", length = 10)
	public Date getDatePaiement() {
		return this.datePaiement;
	}

	public void setDatePaiement(Date datePaiement) {
		this.datePaiement = datePaiement;
	}

	@Column(name = "somme", precision = 22, scale = 0)
	public Double getSomme() {
		return this.somme;
	}

	public void setSomme(Double somme) {
		this.somme = somme;
	}


}
