package main.java.com.hotel.model;
// Generated 19 avr. 2017 12:27:09 by Hibernate Tools 5.2.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "reservation", catalog = "hotel")
public class Reservation implements java.io.Serializable {

	private int idR;
	private Chambre chambre;
	private Client client;
	private Utilisateur utilisateur;
	private Date dateReser;
	private Date dateArri;
	private Date dateSortie;
	private Date dateNaissance;
	private Integer idP;
	private Set<Facture> factures = new HashSet(0);

	public Reservation() {
	}

	public Reservation(int idR) {
		this.idR = idR;
	}

	public Reservation(int idR, Chambre chambre, Client client, Utilisateur utilisateur, Date dateReser, Date dateArri,
			Date dateSortie, Date dateNaissance, Integer idP, Set factures) {
		this.idR = idR;
		this.chambre = chambre;
		this.client = client;
		this.utilisateur = utilisateur;
		this.dateReser = dateReser;
		this.dateArri = dateArri;
		this.dateSortie = dateSortie;
		this.dateNaissance = dateNaissance;
		this.idP = idP;
		this.factures = factures;
	}

	@Id

	@Column(name = "idR", unique = true, nullable = false)
	public int getIdR() {
		return this.idR;
	}

	public void setIdR(int idR) {
		this.idR = idR;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idC")
	public Chambre getChambre() {
		return this.chambre;
	}

	public void setChambre(Chambre chambre) {
		this.chambre = chambre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCl")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idU")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateReser", length = 10)
	public Date getDateReser() {
		return this.dateReser;
	}

	public void setDateReser(Date dateReser) {
		this.dateReser = dateReser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateArri", length = 10)
	public Date getDateArri() {
		return this.dateArri;
	}

	public void setDateArri(Date dateArri) {
		this.dateArri = dateArri;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateSortie", length = 10)
	public Date getDateSortie() {
		return this.dateSortie;
	}

	public void setDateSortie(Date dateSortie) {
		this.dateSortie = dateSortie;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "idP")
	public Integer getIdP() {
		return this.idP;
	}

	public void setIdP(Integer idP) {
		this.idP = idP;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservation")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

}
