package main.java.com.hotel.model;
// Generated 30 avr. 2017 02:56:43 by Hibernate Tools 5.2.0.CR1

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = "hotel")
public class Utilisateur implements java.io.Serializable {

    private IntegerProperty idUser;
    private StringProperty nom;
    private StringProperty prenom;
    private StringProperty tel;
    private StringProperty type;
    private StringProperty username;
    private String password;


    public Utilisateur() {
        this.idUser = new SimpleIntegerProperty();
        this.nom = new SimpleStringProperty();
        this.prenom = new SimpleStringProperty();
        this.tel = new SimpleStringProperty();
        this.type = new SimpleStringProperty();
        this.username = new SimpleStringProperty();
    }

    public Utilisateur(int idUser) {
        this.idUser = new SimpleIntegerProperty(idUser);
        this.nom = new SimpleStringProperty();
        this.prenom = new SimpleStringProperty();
        this.tel = new SimpleStringProperty();
        this.type = new SimpleStringProperty();
        this.username = new SimpleStringProperty();
    }

    public Utilisateur(int idUser, String nom, String prenom, String tel, String type, String username, String password) {
        this.idUser = new SimpleIntegerProperty(idUser);
        this.nom = new SimpleStringProperty(nom);
        this.prenom = new SimpleStringProperty(prenom);
        this.tel = new SimpleStringProperty(tel);
        this.type = new SimpleStringProperty(type);
        this.username = new SimpleStringProperty(username);
        this.password = password;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idUser", unique = true, nullable = false)
    public Integer getIdUser() {
        return this.idUser.get();
    }

    public void setIdUser(int idUser) {
        this.idUser.set(idUser);
    }

    @Column(name = "nom", length = 20)
    public String getNom() {
        return this.nom.get();
    }

    public void setNom(String nom) {
        this.nom.set(nom);
    }

    @Column(name = "prenom", length = 20)
    public String getPrenom() {
        return this.prenom.get();
    }

    public void setPrenom(String prenom) {
        this.prenom.set(prenom);
    }

    @Column(name = "tel", length = 15)
    public String getTel() {
        return this.tel.get();
    }

    public void setTel(String tel) {
        this.tel.set(tel);
    }

    @Column(name = "type", length = 2)
    public String getType() {
        return this.type.get();
    }

    public void setType(String type) {
        this.type.set(type);
    }

    @Column(name = "username", length = 45)
    public String getUsername() {
        return this.username.get();
    }

    public void setUsername(String username) {
        this.username.set(username);
    }

    @Column(name = "password", length = 64)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public IntegerProperty idUserProperty() {
        return idUser;
    }

    public StringProperty nomProperty() {
        return nom;
    }

    public StringProperty prenomProperty() {
        return prenom;
    }

    public StringProperty telProperty() {
        return tel;
    }

    public StringProperty typeProperty() {
        return type;
    }

    public StringProperty usernameProperty() {
        return username;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Utilisateur that = (Utilisateur) o;

        if (getIdUser() != null ? getIdUser() !=(that.getIdUser()) : that.getIdUser() != null) return false;
        if (getNom() != null ? !getNom().equals(that.getNom()) : that.getNom() != null) return false;
        if (getPrenom() != null ? !getPrenom().equals(that.getPrenom()) : that.getPrenom() != null) return false;
        if (getTel() != null ? !getTel().equals(that.getTel()) : that.getTel() != null) return false;
        if (getType() != null ? !getType().equals(that.getType()) : that.getType() != null) return false;
        if (getUsername() != null ? !getUsername().equals(that.getUsername()) : that.getUsername() != null)
            return false;
        return getPassword() != null ? getPassword().equals(that.getPassword()) : that.getPassword() == null;
    }

    @Override
    public int hashCode() {
        int result = idUserProperty() != null ? getIdUser().hashCode() : 0;
        result = 31 * result + (getNom() != null ? getNom().hashCode() : 0);
        result = 31 * result + (getPrenom() != null ? getPrenom().hashCode() : 0);
        result = 31 * result + (getTel() != null ? getTel().hashCode() : 0);
        result = 31 * result + (getType() != null ? getType().hashCode() : 0);
        result = 31 * result + (getUsername() != null ? getUsername().hashCode() : 0);
        result = 31 * result + (getPassword() != null ? getPassword().hashCode() : 0);
        return result;
    }
}
